FROM php:7.0-fpm
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    git \
    zlib1g-dev libicu-dev g++ \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) \ 
    mysqli \
    gd \
    opcache \
    intl \
    # && pecl install xdebug \
    # && docker-php-ext-enable xdebug
